### ISSUE TITLE
GetChunk can return nil, nil but other code doesn't really expect that.

### ISSUE THREAD

**Issue by gholt** [creiht/formic#60]

**Comment by gholt** [comment]
Just mounted the fs and then did an `ls` in it's root dir.

```
2016/05/05 15:46:33 Inside InitFs
2016/05/05 15:46:36 Inside handleGetattr
2016/05/05 15:46:36 Getattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=2656] 0x0 fl=0
2016/05/05 15:46:36 Getattr valid=5s ino=1 size=0 mode=drwxrwxr-x
2016/05/05 15:46:36 Inside handleOpen
2016/05/05 15:46:36 Open [ID=0x3 Node=0x1 Uid=0 Gid=0 Pid=2656] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/05 15:46:36 Open 0x0 fl=0
2016/05/05 15:46:36 Inside handleRead
2016/05/05 15:46:36 Read [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=2656] 0x0 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/05 15:46:36 DirEntries:<name:"many" attr:<inode:13927158233081840262 atime:1461951826 mtime:1461951826 ctime:1461951826 crtime:1461951826 mode:2147484096 > > DirEntries:<name:"src" attr:<inode:13925725046501802198 atime:1458151896 mtime:1461004266 ctime:1461780977 crtime:1461780977 mode:2147484096 > > FileEntries:<name:"src.tar" > FileEntries:<name:"usr.tar" attr:<inode:13926501351631618350 atime:1461873519 mtime:1461881776 ctime:1461873519 crtime:1461873519 mode:384 size:1253857280 > >
2016/05/05 15:46:36 name:"many" attr:<inode:13927158233081840262 atime:1461951826 mtime:1461951826 ctime:1461951826 crtime:1461951826 mode:2147484096 >
2016/05/05 15:46:36 name:"src" attr:<inode:13925725046501802198 atime:1458151896 mtime:1461004266 ctime:1461780977 crtime:1461780977 mode:2147484096 >
2016/05/05 15:46:36 name:"src.tar"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40541b]

goroutine 23 [running]:
panic(0x932460, 0xc820010100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*fs).handleRead(0xc820133920, 0xc8201860e0)
        /root/src/github.com/creiht/formic/cfs/fs.go:318 +0x9bb
main.(*fs).handle(0xc820133920, 0x7f82a268f5b0, 0xc8201860e0)
        /root/src/github.com/creiht/formic/cfs/fs.go:56 +0xc0
main.(*server).serve.func1(0xc82015fd00, 0x7f82a268f5b0, 0xc8201860e0)
        /root/src/github.com/creiht/formic/cfs/main.go:53 +0x6d
created by main.(*server).serve
        /root/src/github.com/creiht/formic/cfs/main.go:54 +0x16d
```
