### ISSUE TITLE
another panic

### ISSUE THREAD

**Issue by pandemicsyn** [creiht/formic#66]
```
root@florian-aio:formic (master)# cfs mount iad://8fcb053a-0cfd-4fdb-8b1d-f866fc988a11 /mnt/cfs -o rw
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4026e6]

goroutine 572 [running]:
panic(0x9323a0, 0xc8200100d0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.(*fs).handleGetattr(0xc8201966f0, 0xc820098f80)
    /root/go/src/github.com/creiht/formic/cfs/fs.go:217 +0x436
main.(*fs).handle(0xc8201966f0, 0x7f5cad02f600, 0xc820098f80)
    /root/go/src/github.com/creiht/formic/cfs/fs.go:44 +0x7b2
main.(*server).serve.func1(0xc82012aba0, 0x7f5cad02f600, 0xc820098f80)
    /root/go/src/github.com/creiht/formic/cfs/main.go:53 +0x6d
created by main.(*server).serve
    /root/go/src/github.com/creiht/formic/cfs/main.go:54 +0x16d
```

**Comment by gholt** [comment]
In the formic backend logs, here are the last so many lines:

```
May 10 19:19:30 api02 formicd[7576]: 2016/05/10 19:19:30 ITEMS:  [{6787041867127060445 10391392971362398246 1462243347713180 [8 1 18 6 112 98 117 116 105 108 26 16 24 53 227 26 164 196 77 159 208 164 179 158 185 142 175 69]}]
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 8a14f7c2d6f6e69 5c859935b14ffeaf: returning at point2: 1462243347713379 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb8\x8aŸ\x0f"
May 10 19:19:30 api02 formicd[7576]: 2016/05/10 19:19:30 Unmarshaled Inode([24 53 227 26 164 196 77 159 208 164 179 158 185 142 175 69]): version:1 isDir:true attr:<inode:13929603692677300284 atime:1462243347 mtime:1462243347 ctime:1462243347 crtime:1462243347 mode:2147484141 > inode:13929603692677300284
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read fcf9d6028291fb3e 4c0132a008b9179a: returning at point2: 1462243347707917 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbb\x80\x80ș\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbb\x80\x80ș\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb4օ\xb5\x04"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read fcf9d6028291fb3e 4c0132a008b9179a: returning at point2: 1462243347707917 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbb\x80\x80ș\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbb\x80\x80ș\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb4օ\xb5\x04"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read fcf9d6028291fb3e 4c0132a008b9179a: returning at point2: 1462243347707917 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbb\x80\x80ș\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbb\x80\x80ș\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb4օ\xb5\x04"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replGroupStore Read fcf9d6028291fb3e 4c0132a008b9179a 5e306a9e6dcff7dd 9035a4d9fb8bf026: returning at point2: 1462243347713180 "\b\x01\x12\x06pbutil\x1a\x10\x185\xe3\x1a\xa4\xc4M\x9fФ\xb3\x9e\xb9\x8e\xafE"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 8a14f7c2d6f6e69 5c859935b14ffeaf: returning at point2: 1462243347713379 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb8\x8aŸ\x0f"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 8a14f7c2d6f6e69 5c859935b14ffeaf: returning at point2: 1462243347713379 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb8\x8aŸ\x0f"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 8a14f7c2d6f6e69 5c859935b14ffeaf: returning at point2: 1462243347713379 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbc\x80\x80\xe0\x99\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb8\x8aŸ\x0f"
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read fcf9d6028291fb3e 4c0132a008b9179a: returning at point2: 1462243347707917 "\b\x01\x12P\b\x01\x10\x01\x1a1\b\xbb\x80\x80ș\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050타\x80\b8\x00@\x00H\x00P\x00 \x00(\xbb\x80\x80ș\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x00X\x00`\x00\x18\xb4օ\xb5\x04"
May 10 19:19:30 api02 formicd[7576]: 2016/05/10 19:19:30 ITEMS:  [{3527754229678760220 4806855995094865508 1462243347732839 [8 1 18 9 101 110 99 111 100 101 46 103 111 26 16 149 255 71 228 223 201 193 174 167 66 102 126 146 193 29 0]} {14538022375924460204 15795168093099471621 1462243347721592 [8 1 18 9 100 101 99 111 100 101 46 103 111 26 16 25 180 220 169 255 142 246 223 32 197 130 159 175 68 1 22]}]
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read a9fed331b5045c5b 1f6e2d0063dc7167: returning at point2: 1462243347735164 "\b\x01\x12Q\b\x01\x10\x00\x1a/\b\xbe\x80\x80\xac\x9a\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050\xa4\x038\x00@\xe6\vH\x00P\x00 \x00(\xbe\x80\x80\xac\x9a\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x01X\x80\x80\x04`\xe6\v\x18֝\xe7\xd0\x02"
May 10 19:19:30 api02 formicd[7576]: 2016/05/10 19:19:30 Unmarshaled Inode([149 255 71 228 223 201 193 174 167 66 102 126 146 193 29 0]): version:1 attr:<inode:13929603692836683838 atime:1462243347 mtime:1462243347 ctime:1462243347 crtime:1462243347 mode:420 size:1510 > inode:13929603692836683838 blocks:1 blockSize:65536 lastBlock:1510
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 747e3221a79d6ede 4c3ebc53e5280bfc: returning at point2: 1462243347725949 "\b\x01\x12Q\b\x01\x10\x00\x1a/\b\xbd\x80\x80\x80\x9a\x98\xf9\xa7\xc1\x01\x10\x93\xa0\xa0\xb9\x05\x18\x93\xa0\xa0\xb9\x05 \x93\xa0\xa0\xb9\x05(\x93\xa0\xa0\xb9\x050\xa4\x038\x00@\x94\x16H\x00P\x00 \x00(\xbd\x80\x80\x80\x9a\x98\xf9\xa7\xc1\x010\x008\x00B\x00P\x01X\x80\x80\x04`\x94\x16\x18\xe4\x96\xde\xc6\x0e"
May 10 19:19:30 api02 formicd[7576]: 2016/05/10 19:19:30 Unmarshaled Inode([25 180 220 169 255 142 246 223 32 197 130 159 175 68 1 22]): version:1 attr:<inode:13929603692744409149 atime:1462243347 mtime:1462243347 ctime:1462243347 crtime:1462243347 mode:420 size:2836 > inode:13929603692744409149 blocks:1 blockSize:65536 lastBlock:2836
May 10 19:19:30 api02 formicd[7576]: DEBUG: replValueStore Read 8a14f7c2d6f6e69 5c859935b14ffeaf: returning at point2: 1462243347713379 ""
```

**Comment by pandemicsyn** [comment]
with debug info

```
2016/05/10 19:21:47 Running Lookup for flag.go
2016/05/10 19:21:47 Lookup [ID=0x2812 Node=0xc1500cb8b08002db Uid=0 Gid=0 Pid=23744] "flag.go"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x403324]

goroutine 17564 [running]:
panic(0x9323a0, 0xc8200100d0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.(*fs).handleLookup(0xc82020e1e0, 0xc82736c380)
    /root/go/src/github.com/creiht/formic/cfs/fs.go:244 +0x6b4
main.(*fs).handle(0xc82020e1e0, 0x7f2dbe0b0b30, 0xc82736c380)
    /root/go/src/github.com/creiht/formic/cfs/fs.go:47 +0x80e
main.(*server).serve.func1(0xc8201360c0, 0x7f2dbe0b0b30, 0xc82736c380)
    /root/go/src/github.com/creiht/formic/cfs/main.go:53 +0x6d
created by main.(*server).serve
    /root/go/src/github.com/creiht/formic/cfs/main.go:54 +0x16d
```

**Comment by pandemicsyn** [comment]
target varies every time.
