### ISSUE TITLE
Running bonnie++ test creates a "slice bounds out of range"

### ISSUE THREAD

**Issue by letterj** [creiht/formic#8]
$ bonnie++ -d /tmp/test01 -s 0 -n 1:1024M:64M:4:8K -m FSAAS -f -b -u root
Using uid:0, gid:0.
Create files in sequential order...Can't write data.
Cleaning up test directory after error.
Bonnie: drastic I/O error (rmdir): Transport endpoint is not connected

cfuse:
 Gid=0 Pid=25638] 0x0 8192 @201703424 fl=0 lock=0 ffl=OpenWriteOnly
2015/12/01 20:19:37 Inside handleGetxattr
2015/12/01 20:19:37 Getxattr [ID=0x1f8198 Node=0xbfc53e8ec9800418 Uid=0 Gid=0 Pid=25638] "security.capability" 0 @0
2015/12/01 20:19:37 Getxattr
2015/12/01 20:19:37 Inside handleWrite
2015/12/01 20:19:37 Writing 8192 bytes at offset 201711616
2015/12/01 20:19:37 Write [ID=0x1f8199 Node=0xbfc53e8ec9800418 Uid=0 Gid=0 Pid=25638] 0x0 8192 @201711616 fl=0 lock=0 ffl=OpenWriteOnly
2015/12/01 20:19:47 Write to file failed: rpc error: code = 4 desc = "context deadline exceeded"

formicd:
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: panic: runtime error: slice bounds out of range
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: goroutine 16436 [running]:
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: main.(_apiServer).Write(0xc8201a5630, 0x2b55f5ed7fe8, 0xc8204df740, 0xc8204df860, 0xc820038b58, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/github.com/creiht/formic/formicd/api.go:148 +0x570
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: github.com/creiht/formic/proto._Api_Write_Handler(0x8c12c0, 0xc8201a5630, 0x2b55f5ed7fe8, 0xc8204df740, 0xc8204df830, 0x0, 0x0, 
0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/github.com/creiht/formic/proto/oort_api.pb.go:625 +0x135
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: google.golang.org/grpc.(_Server).processUnaryRPC(0xc82019fd40, 0x2b55f5ed7df8, 0xc820231cb0, 0xc82040c300, 0xc8201a8ec0, 0xb2b1e
8, 0xc8204df710, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/google.golang.org/grpc/server.go:350 +0x866
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: google.golang.org/grpc.(_Server).handleStream(0xc82019fd40, 0x2b55f5ed7df8, 0xc820231cb0, 0xc82040c300, 0xc8204df710)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/google.golang.org/grpc/server.go:467 +0x743
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: google.golang.org/grpc.(_Server).Serve.func2.1.1(0xc82019fd40, 0x2b55f5ed7df8, 0xc820231cb0, 0xc82040c300, 0xc8204df710, 0xc8200
0b3c0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/google.golang.org/grpc/server.go:278 +0x49
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: created by google.golang.org/grpc.(_Server).Serve.func2.1
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/google.golang.org/grpc/server.go:280 +0x5ac
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: goroutine 1 [IO wait]:
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.runtime_pollWait(0x2b55f6ce6798, 0x72, 0xc82000a160)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.(_pollDesc).Wait(0xc82017a370, 0x72, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.(_pollDesc).WaitRead(0xc82017a370, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.(_netFD).accept(0xc82017a310, 0x0, 0x2b55f6ceab20, 0xc820247b40)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/net/fd_unix.go:408 +0x27c
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.(_TCPListener).AcceptTCP(0xc8200ec0e0, 0xc8200f9bd8, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: net.(_TCPListener).Accept(0xc8200ec0e0, 0x0, 0x0, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: google.golang.org/grpc.(*Server).Serve(0xc82019fd40, 0x2b55f6ce5818, 0xc8200ec0e0, 0x0, 0x0)
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/google.golang.org/grpc/server.go:224 +0x1c1
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: main.main()
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: /root/go/src/github.com/creiht/formic/formicd/main.go:80 +0x9b1
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: goroutine 17 [syscall, locked to thread]:
Nov 30 22:29:24 letterj-aio.rackfs.com formic[16726]: runtime.goexit()

**Comment by letterj** [comment]
This has been fixed
